#----------------------------------------------------------------------#
#  ASTEROID 2.41 - OS/2 port build (Open Watcom)                      #
#                                                                      #
#  Targets:                                                            #
#    all      -> ASTEROID.EXE (PM app, bind resources)                 #
#                ASTEROID.DLL (16-bit font module, bound resources)    #
#                ASTEROID.HLP (IPF help)                               #
#    app      -> ASTEROID.EXE only                                     #
#    fontdll  -> ASTEROID.DLL only                                     #
#    help     -> ASTEROID.HLP only                                     #
#    clean    -> remove everything under bin\                      #
#                                                                      #
#  Notes:                                                              #
#    - Run via compile.cmd (sets WATCOM/INCLUDE/PATH).                 #
#    - The font module resources come from src\font\ASTEROID.RES       #
#      (FONTDIRECTORY type 6/name 1 + faces type 1000/names 100/200).  #
#      OW wrc cannot build GPI font resources from RC FONT statements  #
#      (it corrupts FAT payloads), so the .RES is generated by         #
#      fontdll_res.py (see README) and merely bound here.              #
#----------------------------------------------------------------------#

WATCOM    = $(%WATCOM)

INC       = $(WATCOM)\h;$(WATCOM)\h\os2;src
CC        = wcc386
A86       = wasm
WLINK     = wlink
WRC       = wrc
IPFC      = wipfc

OUT       = bin

CFLAGS    = -bt=os2 -5r -mf -zq -w4 -e25 -Oaxt -d0 -i=src
AFLAGS    = -bt=os2 -zq
LFLAGS    = option quiet, map
RCFLAGS   = -r -bt=os2
BINDWF    = -q -bt=os2

TARGETS   = $(OUT)\ASTEROID.EXE $(OUT)\ASTEROID.DLL $(OUT)\ASTEROID.HLP

all       : $(TARGETS)

$(OUT)    :
	@if not exist $(OUT) mkdir $(OUT)

#----------------------------------------------------------------- help
$(OUT)\ASTEROID.HLP : help\ASTEROID.IPF $(OUT)
	$(IPFC) -q -o $(OUT)\ASTEROID.HLP help\ASTEROID.IPF

#------------------------------------------------------------ app
$(OUT)\ASTEROID.OBJ : src\ASTEROID.C src\ASTEROID.H src\PMDEFS.H src\LANG.H $(OUT)
	$(CC) $(CFLAGS) -fo=$@ src\ASTEROID.C

$(OUT)\SUBS.OBJ : src\SUBS.C src\ASTEROID.H src\PMDEFS.H src\LANG.H $(OUT)
	$(CC) $(CFLAGS) -fo=$@ src\SUBS.C

$(OUT)\ASTEROID.RES : src\ASTEROID.RC src\PMDEFS.H src\ASTEROID.ICO $(OUT)
	$(WRC) $(RCFLAGS) -fo=$@ -i=src src\ASTEROID.RC

$(OUT)\ASTEROID.EXE : $(OUT)\ASTEROID.OBJ $(OUT)\SUBS.OBJ $(OUT)\ASTEROID.RES
	$(WLINK) $(LFLAGS) system os2v2 pm option heapsize=1024 option stack=65536 export ClientWndProc export AboutDlgProc export KeyDlgProc name $(OUT)\ASTEROID.EXE file $(OUT)\ASTEROID.OBJ, $(OUT)\SUBS.OBJ
	$(WRC) $(BINDWF) -fe=$@ $(OUT)\ASTEROID.RES $@

#---------------------------------------------------------- font dll
$(OUT)\FONTDLL.OBJ : src\font\ASTEROID.ASM $(OUT)
	$(A86) $(AFLAGS) -fo=$@ src\font\ASTEROID.ASM

$(OUT)\ASTEROID.DLL : $(OUT)\FONTDLL.OBJ src\font\ASTEROID.RES
	$(WLINK) $(LFLAGS) system os2 dll libpath $(WATCOM)\lib name $(OUT)\ASTEROID.DLL file $(OUT)\FONTDLL.OBJ
	$(WRC) $(BINDWF) -fe=$@ src\font\ASTEROID.RES $@

#-------------------------------------------------------------- misc
app       : $(OUT)\ASTEROID.EXE

fontdll   : $(OUT)\ASTEROID.DLL

help      : $(OUT)\ASTEROID.HLP

# stage - host-runnable subset: everything except the OS/2-only
# wlink output formats and the -fe binds (those need the OS/2 build).
stage     : $(OUT)\ASTEROID.OBJ $(OUT)\SUBS.OBJ $(OUT)\ASTEROID.RES $(OUT)\FONTDLL.OBJ $(OUT)\ASTEROID.HLP

clean     :
	@if exist bin del bin\ASTEROID.EXE >nul
	@if exist bin del bin\ASTEROID.DLL >nul
	@if exist bin del bin\ASTEROID.HLP >nul
	@if exist bin del bin\ASTEROID.RES >nul
	@if exist bin del bin\ASTEROID.OBJ >nul
	@if exist bin del bin\SUBS.OBJ >nul
	@if exist bin del bin\FONTDLL.OBJ >nul
	@if exist bin rd bin >nul